export const rules = {
  m9uiwyakk94rhynzsjg: {
    id: "m9uiwyakk94rhynzsjg",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:46.940Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.05",
    parentSectionId: "m9uiwqnn61qgkddizl8",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  m9uiwyak6648y2ch6ov: {
    id: "m9uiwyak6648y2ch6ov",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:46.940Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.07",
    parentSectionId: "m9uiwqnn61qgkddizl8",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  m9uix1xn3ewzavvi88: {
    id: "m9uix1xn3ewzavvi88",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:51.659Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.05",
    parentSectionId: "m9uiwqnnyi80qsl524r",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uix1xnkjtapmvfi8l: {
    id: "m9uix1xnkjtapmvfi8l",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:51.659Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.07",
    parentSectionId: "m9uiwqnnyi80qsl524r",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  m9uix9bftk68lh62gbr: {
    id: "m9uix9bftk68lh62gbr",
    name: "No of loan cycles",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:01.227Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.00",
    parentSectionId: "m9uiwqnof2915l2c9a",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "LOAN_CYCLES",
    properties: [
      { name: "<=1", id: "LOAN_CYCLES_1", score: 20 },
      { name: ">1 and <=3", id: "LOAN_CYCLES_3", score: 40 },
      { name: ">3 and <=5", id: "LOAN_CYCLES_5", score: 60 },
      { name: ">5 and <=10", id: "LOAN_CYCLES_10", score: 80 },
      { name: ">10", id: "LOAN_CYCLES_10", score: 100 },
    ],
  },
  m9uix9bfyk8l63iywg9: {
    id: "m9uix9bfyk8l63iywg9",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:01.227Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.10",
    parentSectionId: "m9uiwqnof2915l2c9a",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixekjcad25pms26r: {
    id: "m9uixekjcad25pms26r",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:08.035Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.05",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uixekj9l97hanzd0l: {
    id: "m9uixekj9l97hanzd0l",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:08.035Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.74",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixyiry3qufr19hfg: {
    id: "m9uixyiry3qufr19hfg",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.63",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uixyirvedh0g9ux4d: {
    id: "m9uixyirvedh0g9ux4d",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.09",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixyirmhwbptv0am: {
    id: "m9uixyirmhwbptv0am",
    name: "Loan installment income percentage",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.67",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "LOAN_INSTALLMENT_INCOME_PERCENTAGE",
    properties: [
      { name: "<=10", id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_10", score: 100 },
      {
        name: ">10 and <=20",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_20",
        score: 80,
      },
      {
        name: ">20 and <=30",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_30",
        score: 60,
      },
      {
        name: ">30 and <=40",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_40",
        score: 40,
      },
      { name: ">40", id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_40", score: 20 },
    ],
  },
  m9uixyirh6h3ax7a6h: {
    id: "m9uixyirh6h3ax7a6h",
    name: "Debt handling capacity",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.77",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "DEBT_HANDLING_CAPACITY",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  m9uusebbqob7pzl8mui: {
    id: "m9uusebbqob7pzl8mui",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.815Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.05",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  m9uusebb6nf8ei8pnou: {
    id: "m9uusebb6nf8ei8pnou",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.815Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.07",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  m9uusebcvcnu764jvkh: {
    id: "m9uusebcvcnu764jvkh",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.816Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.38",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uusebc3ofowxjf2qw: {
    id: "m9uusebc3ofowxjf2qw",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.816Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.83",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  m9uusebdvt65d21zf88: {
    id: "m9uusebdvt65d21zf88",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.817Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.93",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uusebdak9s3veyfj9: {
    id: "m9uusebdak9s3veyfj9",
    name: "Employment Type",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.817Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.87",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EMPLOYMENT_TYPE",
    properties: [
      {
        name: "Employees of Government and Statutory Bodies",
        id: "PERMANENT",
        score: 100,
      },
      {
        name: "Employees of Private Sector / Professionals with Fixed Income",
        id: "CONTRACT",
        score: 80,
      },
      {
        name: "Professionals with Non-Fixed Income",
        id: "TEMPORARY",
        score: 60,
      },
      { name: "Self-Employed / Own Business", id: "INTERNSHIP", score: 40 },
    ],
  },
  maamw56g27p28esi3l2: {
    id: "maamw56g27p28esi3l2",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.488Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.95",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  maamw56h96mc0x4idiq: {
    id: "maamw56h96mc0x4idiq",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.489Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.32",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  maamw56h77b7gu5xa6v: {
    id: "maamw56h77b7gu5xa6v",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.489Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.73",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  maamw56h3hy70n6qnfi: {
    id: "maamw56h3hy70n6qnfi",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.489Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.10",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  maamw56h685cvoghbnh: {
    id: "maamw56h685cvoghbnh",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.489Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.62",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  maamw56h8gdcm98zbtr: {
    id: "maamw56h8gdcm98zbtr",
    name: "Employment Type",
    lastEdited: "",
    createdAt: "2025-05-05T05:22:26.489Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.57",
    parentSectionId: "maamuphcxog0872supj",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "EMPLOYMENT_TYPE",
    properties: [
      {
        name: "Employees of Government and Statutory Bodies",
        id: "PERMANENT",
        score: 100,
      },
      {
        name: "Employees of Private Sector / Professionals with Fixed Income",
        id: "CONTRACT",
        score: 80,
      },
      {
        name: "Professionals with Non-Fixed Income",
        id: "TEMPORARY",
        score: 60,
      },
      { name: "Self-Employed / Own Business", id: "INTERNSHIP", score: 40 },
    ],
  },
  maamyltc4u6sq8gys1h: {
    id: "maamyltc4u6sq8gys1h",
    name: "Presence of regulated financial system",
    lastEdited: "",
    createdAt: "2025-05-05T05:24:21.360Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.68",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "presenceOfRegulatedFinancialSystem",
    properties: [
      { name: "No", id: "NO", score: 20 },
      { name: "Yes", id: "YES", score: 60 },
    ],
  },
  maamyltcmsohnannblh: {
    id: "maamyltcmsohnannblh",
    name: "CRIB record",
    lastEdited: "",
    createdAt: "2025-05-05T05:24:21.360Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.22",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "CRIB_RECORD",
    properties: [
      { name: "No CRIB Record", id: "NO_CRIB_RECORD", score: 100 },
      { name: "Good CRIB Record", id: "GOOD_CRIB_RECORD", score: 80 },
      { name: "Bad CRIB Record", id: "BAD_CRIB_RECORD", score: 60 },
      { name: "Very Bad CRIB Record", id: "VERY_BAD_CRIB_RECORD", score: 40 },
    ],
  },
  maamyz20ey9cseuvbdo: {
    id: "maamyz20ey9cseuvbdo",
    name: "Debt handling capacity",
    lastEdited: "",
    createdAt: "2025-05-05T05:24:38.520Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.63",
    parentSectionId: "maamuphdge9kpmizzia",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "DEBT_HANDLING_CAPACITY",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  maarhzg4j0pwd31uafj: {
    id: "maarhzg4j0pwd31uafj",
    name: "Presence of regulated financial system",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:23.956Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.94",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "presenceOfRegulatedFinancialSystem",
    properties: [
      { name: "No", id: "NO", score: 20 },
      { name: "Yes", id: "YES", score: 60 },
    ],
  },
  maarhzg5e7gq8iv016w: {
    id: "maarhzg5e7gq8iv016w",
    name: "CRIB record",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:23.957Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.68",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "CRIB_RECORD",
    properties: [
      { name: "No CRIB Record", id: "NO_CRIB_RECORD", score: 100 },
      { name: "Good CRIB Record", id: "GOOD_CRIB_RECORD", score: 80 },
      { name: "Bad CRIB Record", id: "BAD_CRIB_RECORD", score: 60 },
      { name: "Very Bad CRIB Record", id: "VERY_BAD_CRIB_RECORD", score: 40 },
    ],
  },
  maarhzg5d1qec9enbyl: {
    id: "maarhzg5d1qec9enbyl",
    name: "LTV Ratio (For Vehicle & Housing Loans)",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:23.957Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.94",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "ltvRatioForVehicleHousingLoans",
    properties: [
      { name: "<=30%", id: "LESS_THAN_EQUEL_30", score: 100 },
      { name: ">30% and <=45", id: "BETWEEN_30_AND_45", score: 75 },
      { name: ">45% and <=60", id: "BETWEEN_45_AND_60", score: 50 },
      { name: ">60%", id: "MORE_THAN_60", score: 0 },
    ],
  },
  maarii3o4y3uusyypgr: {
    id: "maarii3o4y3uusyypgr",
    name: "Presence of regulated financial system",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:48.132Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.56",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "presenceOfRegulatedFinancialSystem",
    properties: [
      { name: "No", id: "NO", score: 20 },
      { name: "Yes", id: "YES", score: 60 },
    ],
  },
  maarii3og38za37fstd: {
    id: "maarii3og38za37fstd",
    name: "CRIB record",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:48.132Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.87",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "CRIB_RECORD",
    properties: [
      { name: "No CRIB Record", id: "NO_CRIB_RECORD", score: 100 },
      { name: "Good CRIB Record", id: "GOOD_CRIB_RECORD", score: 80 },
      { name: "Bad CRIB Record", id: "BAD_CRIB_RECORD", score: 60 },
      { name: "Very Bad CRIB Record", id: "VERY_BAD_CRIB_RECORD", score: 40 },
    ],
  },
  maarii3oel28gfy6ebq: {
    id: "maarii3oel28gfy6ebq",
    name: "LTV Ratio (For Vehicle & Housing Loans)",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:48.132Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.83",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "ltvRatioForVehicleHousingLoans",
    properties: [
      { name: "<=30%", id: "LESS_THAN_EQUEL_30", score: 100 },
      { name: ">30% and <=45", id: "BETWEEN_30_AND_45", score: 75 },
      { name: ">45% and <=60", id: "BETWEEN_45_AND_60", score: 50 },
      { name: ">60%", id: "MORE_THAN_60", score: 0 },
    ],
  },
  maarii3pi78ptq0ogxh: {
    id: "maarii3pi78ptq0ogxh",
    name: "Salary Assignment",
    lastEdited: "",
    createdAt: "2025-05-05T07:31:48.133Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.39",
    parentSectionId: "maamuphdnvzhch5rsz",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "salaryAssignment",
    properties: [
      {
        name: "Mo-Re 238 agreement in place",
        id: "MORE_238_AGREEMENT_IN_PLACE",
        score: 100,
      },
      {
        name: "Salary assigned to RDB",
        id: "SALARY_ASSIGNED_TO_RDB",
        score: 50,
      },
      {
        name: "Salary not assigned to RDB",
        id: "SALARY_NOT_ASSIGNED_TO_RDB",
        score: 0,
      },
    ],
  },
  maarivgtw8qo36ikco: {
    id: "maarivgtw8qo36ikco",
    name: "Debt handling capacity",
    lastEdited: "",
    createdAt: "2025-05-05T07:32:05.453Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.79",
    parentSectionId: "maamuphdge9kpmizzia",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "DEBT_HANDLING_CAPACITY",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  maarivgtbkw9hkah588: {
    id: "maarivgtbkw9hkah588",
    name: "Monthly income to No of family members",
    lastEdited: "",
    createdAt: "2025-05-05T07:32:05.453Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.56",
    parentSectionId: "maamuphdge9kpmizzia",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId: "monthlyIncomeNoFamilyMembers",
    properties: [
      { name: "More than LKR 35000", id: "MORE_THAN_LKR_35000", score: 100 },
      {
        name: "More than LKR 25000 and up to LKR 35000",
        id: "MORE_THAN_LKR_25000_AND_UP_TO_LKR_35000",
        score: 80,
      },
      {
        name: "More than LKR 20000 and up to LKR 25000",
        id: "MORE_THAN_LKR_20000_AND_UP_TO_LKR_25000",
        score: 60,
      },
      {
        name: "More than LKR 15000 and up to LKR 20000",
        id: "MORE_THAN_LKR_15000_AND_UP_TO_LKR_20000",
        score: 40,
      },
      { name: "Less than LKR 15000", id: "LESS_THAN_LKR_15000", score: 20 },
    ],
  },
  maarivgtx7dgcmai0y: {
    id: "maarivgtx7dgcmai0y",
    name: "% of loan installment (outstanding loans + proposed loans) to monthly income",
    lastEdited: "",
    createdAt: "2025-05-05T07:32:05.453Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.55",
    parentSectionId: "maamuphdge9kpmizzia",
    parentTemplateId: "PERSONAL_FINANCE_TEMPLATE",
    parentRuleId:
      "ofLoanInstallmentOutstandingLoansProposedLoansToMonthlyIncome",
    properties: [
      { name: "<=20%", id: "LESS_THAN_EQUEL_20", score: 100 },
      { name: ">20% and <=30%", id: "BETWEEN_20_AND_30", score: 50 },
      { name: ">30% and <=40%", id: "BETWEEN_30_AND_40", score: 25 },
      { name: ">40%", id: "MORE_THAN_40", score: 0 },
    ],
  },
  maasp45wsrey5375ab: {
    id: "maasp45wsrey5375ab",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.276Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.91",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  maasp45wh4smuoclyq7: {
    id: "maasp45wh4smuoclyq7",
    name: "Age-JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.276Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.12",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "AGE_JA",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  maasp45w4sqjqytifjw: {
    id: "maasp45w4sqjqytifjw",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.276Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.82",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  maasp45x083ff66t7aui: {
    id: "maasp45x083ff66t7aui",
    name: "Education level-JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.277Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.34",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EDUCATION_LEVEL_JA",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  maasp45x2yxv6f2nxk4: {
    id: "maasp45x2yxv6f2nxk4",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.277Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.70",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  maasp45xysp9rug96c: {
    id: "maasp45xysp9rug96c",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.277Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.31",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  maasp45y36xwcl4nwui: {
    id: "maasp45y36xwcl4nwui",
    name: "Employment status-JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.278Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.86",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EMPLOYMENT_STATUS_JA",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  maasp45yogobsfmooe: {
    id: "maasp45yogobsfmooe",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.278Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.32",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  maasp45ye3t0714h9ar: {
    id: "maasp45ye3t0714h9ar",
    name: "No of experience in employment - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.278Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.27",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EXPERIENCE_JA",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  maasp45zrjkzlo2u4z: {
    id: "maasp45zrjkzlo2u4z",
    name: "Employment Type",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.279Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.70",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EMPLOYMENT_TYPE",
    properties: [
      {
        name: "Employees of Government and Statutory Bodies",
        id: "PERMANENT",
        score: 100,
      },
      {
        name: "Employees of Private Sector / Professionals with Fixed Income",
        id: "CONTRACT",
        score: 80,
      },
      {
        name: "Professionals with Non-Fixed Income",
        id: "TEMPORARY",
        score: 60,
      },
      { name: "Self-Employed / Own Business", id: "INTERNSHIP", score: 40 },
    ],
  },
  maasp45z1fi1djpohnf: {
    id: "maasp45z1fi1djpohnf",
    name: "Employment Type-JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:04:56.279Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.56",
    parentSectionId: "maasobzg1r1i8s16mbm",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "EMPLOYMENT_TYPE_JA",
    properties: [
      {
        name: "Employees of Government and Statutory Bodies",
        id: "PERMANENT",
        score: 100,
      },
      {
        name: "Employees of Private Sector / Professionals with Fixed Income",
        id: "CONTRACT",
        score: 80,
      },
      {
        name: "Professionals with Non-Fixed Income",
        id: "TEMPORARY",
        score: 60,
      },
      { name: "Self-Employed / Own Business", id: "INTERNSHIP", score: 40 },
    ],
  },
  maasv8p7bnsg8v5p8an: {
    id: "maasv8p7bnsg8v5p8an",
    name: "Monthly income to No of family members",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.091Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.11",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "monthlyIncomeNoFamilyMembers",
    properties: [
      { name: "More than LKR 35000", id: "MORE_THAN_LKR_35000", score: 100 },
      {
        name: "More than LKR 25000 and up to LKR 35000",
        id: "MORE_THAN_LKR_25000_AND_UP_TO_LKR_35000",
        score: 80,
      },
      {
        name: "More than LKR 20000 and up to LKR 25000",
        id: "MORE_THAN_LKR_20000_AND_UP_TO_LKR_25000",
        score: 60,
      },
      {
        name: "More than LKR 15000 and up to LKR 20000",
        id: "MORE_THAN_LKR_15000_AND_UP_TO_LKR_20000",
        score: 40,
      },
      { name: "Less than LKR 15000", id: "LESS_THAN_LKR_15000", score: 20 },
    ],
  },
  maasv8p8bs5rffu0qqr: {
    id: "maasv8p8bs5rffu0qqr",
    name: "Monthly income to No of family members - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.092Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.72",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "monthlyIncomeNoFamilyMembers_JA",
    properties: [
      { name: "More than LKR 35000", id: "MORE_THAN_LKR_35000", score: 100 },
      {
        name: "More than LKR 25000 and up to LKR 35000",
        id: "MORE_THAN_LKR_25000_AND_UP_TO_LKR_35000",
        score: 80,
      },
      {
        name: "More than LKR 20000 and up to LKR 25000",
        id: "MORE_THAN_LKR_20000_AND_UP_TO_LKR_25000",
        score: 60,
      },
      {
        name: "More than LKR 15000 and up to LKR 20000",
        id: "MORE_THAN_LKR_15000_AND_UP_TO_LKR_20000",
        score: 40,
      },
      { name: "Less than LKR 15000", id: "LESS_THAN_LKR_15000", score: 20 },
    ],
  },
  maasv8p8hecg25jivxi: {
    id: "maasv8p8hecg25jivxi",
    name: "% of loan installment (outstanding loans + proposed loans) to monthly income",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.092Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.06",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId:
      "ofLoanInstallmentOutstandingLoansProposedLoansToMonthlyIncome",
    properties: [
      { name: "<=20%", id: "LESS_THAN_EQUEL_20", score: 100 },
      { name: ">20% and <=30%", id: "BETWEEN_20_AND_30", score: 50 },
      { name: ">30% and <=40%", id: "BETWEEN_30_AND_40", score: 25 },
      { name: ">40%", id: "MORE_THAN_40", score: 0 },
    ],
  },
  maasv8p9c828weefgfg: {
    id: "maasv8p9c828weefgfg",
    name: "% of loan installment (outstanding loans + proposed loans) to monthly income -JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.093Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.75",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId:
      "ofLoanInstallmentOutstandingLoansProposedLoansToMonthlyIncome_JA",
    properties: [
      { name: "<=20%", id: "LESS_THAN_EQUEL_20", score: 100 },
      { name: ">20% and <=30%", id: "BETWEEN_20_AND_30", score: 50 },
      { name: ">30% and <=40%", id: "BETWEEN_30_AND_40", score: 25 },
      { name: ">40%", id: "MORE_THAN_40", score: 0 },
    ],
  },
  maasv8p9v3m1lyqsf5i: {
    id: "maasv8p9v3m1lyqsf5i",
    name: "Debt handling capacity",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.093Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.46",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "DEBT_HANDLING_CAPACITY",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  maasv8pa2lmx7sy69gq: {
    id: "maasv8pa2lmx7sy69gq",
    name: "Debt handling capacity - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:09:42.094Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.06",
    parentSectionId: "maasobzgcs5n8z7zr8m",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "DEBT_HANDLING_CAPACITY_JA",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  maat1erf5uxnd0hh91c: {
    id: "maat1erf5uxnd0hh91c",
    name: "Salary Assignment",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.883Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.65",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "salaryAssignment",
    properties: [
      {
        name: "Mo-Re 238 agreement in place",
        id: "MORE_238_AGREEMENT_IN_PLACE",
        score: 100,
      },
      {
        name: "Salary assigned to RDB",
        id: "SALARY_ASSIGNED_TO_RDB",
        score: 50,
      },
      {
        name: "Salary not assigned to RDB",
        id: "SALARY_NOT_ASSIGNED_TO_RDB",
        score: 0,
      },
    ],
  },
  maat1ergngcafh7h3z: {
    id: "maat1ergngcafh7h3z",
    name: "Salary Assignment - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.884Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.66",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "salaryAssignment_JA",
    properties: [
      {
        name: "Mo-Re 238 agreement in place",
        id: "MORE_238_AGREEMENT_IN_PLACE",
        score: 100,
      },
      {
        name: "Salary assigned to RDB",
        id: "SALARY_ASSIGNED_TO_RDB",
        score: 50,
      },
      {
        name: "Salary not assigned to RDB",
        id: "SALARY_NOT_ASSIGNED_TO_RDB",
        score: 0,
      },
    ],
  },
  maat1erhwei9aqhzjxh: {
    id: "maat1erhwei9aqhzjxh",
    name: "LTV Ratio (For Vehicle & Housing Loans)",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.885Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.18",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "ltvRatioForVehicleHousingLoans",
    properties: [
      { name: "<=30%", id: "LESS_THAN_EQUEL_30", score: 100 },
      { name: ">30% and <=45", id: "BETWEEN_30_AND_45", score: 75 },
      { name: ">45% and <=60", id: "BETWEEN_45_AND_60", score: 50 },
      { name: ">60%", id: "MORE_THAN_60", score: 0 },
    ],
  },
  maat1erh8zyebq6wy96: {
    id: "maat1erh8zyebq6wy96",
    name: "CRIB record",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.885Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.62",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "CRIB_RECORD",
    properties: [
      { name: "No CRIB Record", id: "NO_CRIB_RECORD", score: 100 },
      { name: "Good CRIB Record", id: "GOOD_CRIB_RECORD", score: 80 },
      { name: "Bad CRIB Record", id: "BAD_CRIB_RECORD", score: 60 },
      { name: "Very Bad CRIB Record", id: "VERY_BAD_CRIB_RECORD", score: 40 },
    ],
  },
  maat1eriop7vt3a3ehr: {
    id: "maat1eriop7vt3a3ehr",
    name: "CRIB record - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.886Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.15",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "CRIB_RECORD_JA",
    properties: [
      { name: "No CRIB Record", id: "NO_CRIB_RECORD", score: 100 },
      { name: "Good CRIB Record", id: "GOOD_CRIB_RECORD", score: 80 },
      { name: "Bad CRIB Record", id: "BAD_CRIB_RECORD", score: 60 },
      { name: "Very Bad CRIB Record", id: "VERY_BAD_CRIB_RECORD", score: 40 },
    ],
  },
  maat1erj3gcsvyosrc2: {
    id: "maat1erj3gcsvyosrc2",
    name: "Bank relations",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.887Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.39",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "BANK_RELATIONS",
    properties: [
      { name: "No Bank Relations", id: "NO_BANK_RELATIONS", score: 20 },
      { name: "Good Bank Relations", id: "GOOD_BANK_RELATIONS", score: 60 },
      { name: "Bad Bank Relations", id: "BAD_BANK_RELATIONS", score: 40 },
      {
        name: "Very Bad Bank Relations",
        id: "VERY_BAD_BANK_RELATIONS",
        score: 20,
      },
    ],
  },
  maat1erjizl00dm2i2a: {
    id: "maat1erjizl00dm2i2a",
    name: "Bank relations - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.887Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.35",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "BANK_RELATIONS_JA",
    properties: [
      { name: "No Bank Relations", id: "NO_BANK_RELATIONS", score: 20 },
      { name: "Good Bank Relations", id: "GOOD_BANK_RELATIONS", score: 60 },
      { name: "Bad Bank Relations", id: "BAD_BANK_RELATIONS", score: 40 },
      {
        name: "Very Bad Bank Relations",
        id: "VERY_BAD_BANK_RELATIONS",
        score: 20,
      },
    ],
  },
  maat1erkixf3pzf8wb: {
    id: "maat1erkixf3pzf8wb",
    name: "Presence of regulated financial system",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.888Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.15",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "presenceOfRegulatedFinancialSystem",
    properties: [
      { name: "No", id: "NO", score: 20 },
      { name: "Yes", id: "YES", score: 60 },
    ],
  },
  maat1erkvkbbu1g8uhd: {
    id: "maat1erkvkbbu1g8uhd",
    name: "Presence of regulated financial system - JA",
    lastEdited: "",
    createdAt: "2025-05-05T08:14:29.888Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.46",
    parentSectionId: "maasobzglmgv9ibhpw8",
    parentTemplateId: "PERSONAL_FINANCE_MODEL_-_JOINT_BORROWERS",
    parentRuleId: "presenceOfRegulatedFinancialSystem_JA",
    properties: [
      { name: "No", id: "NO", score: 20 },
      { name: "Yes", id: "YES", score: 60 },
    ],
  },
};
