export const sectionRules = {
  m9uiwyakk94rhynzsjg: {
    id: "m9uiwyakk94rhynzsjg",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:46.940Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uiwqnn61qgkddizl8",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  m9uiwyak6648y2ch6ov: {
    id: "m9uiwyak6648y2ch6ov",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:46.940Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uiwqnn61qgkddizl8",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  m9uix1xn3ewzavvi88: {
    id: "m9uix1xn3ewzavvi88",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:51.659Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uiwqnnyi80qsl524r",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uix1xnkjtapmvfi8l: {
    id: "m9uix1xnkjtapmvfi8l",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-04-23T22:46:51.659Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uiwqnnyi80qsl524r",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  m9uix9bftk68lh62gbr: {
    id: "m9uix9bftk68lh62gbr",
    name: "No of loan cycles",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:01.227Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uiwqnof2915l2c9a",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "LOAN_CYCLES",
    properties: [
      { name: "<=1", id: "LOAN_CYCLES_1", score: 20 },
      { name: ">1 and <=3", id: "LOAN_CYCLES_3", score: 40 },
      { name: ">3 and <=5", id: "LOAN_CYCLES_5", score: 60 },
      { name: ">5 and <=10", id: "LOAN_CYCLES_10", score: 80 },
      { name: ">10", id: "LOAN_CYCLES_10", score: 100 },
    ],
  },
  m9uix9bfyk8l63iywg9: {
    id: "m9uix9bfyk8l63iywg9",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:01.227Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uiwqnof2915l2c9a",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixekjcad25pms26r: {
    id: "m9uixekjcad25pms26r",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:08.035Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uixekj9l97hanzd0l: {
    id: "m9uixekj9l97hanzd0l",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:08.035Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixyiry3qufr19hfg: {
    id: "m9uixyiry3qufr19hfg",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uixyirvedh0g9ux4d: {
    id: "m9uixyirvedh0g9ux4d",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uixyirmhwbptv0am: {
    id: "m9uixyirmhwbptv0am",
    name: "Loan installment income percentage",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    score: "0.67",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "LOAN_INSTALLMENT_INCOME_PERCENTAGE",
    properties: [
      { name: "<=10", id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_10", score: 100 },
      {
        name: ">10 and <=20",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_20",
        score: 80,
      },
      {
        name: ">20 and <=30",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_30",
        score: 60,
      },
      {
        name: ">30 and <=40",
        id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_40",
        score: 40,
      },
      { name: ">40", id: "LOAN_INSTALLMENT_INCOME_PERCENTAGE_40", score: 20 },
    ],
  },
  m9uixyirh6h3ax7a6h: {
    id: "m9uixyirh6h3ax7a6h",
    name: "Debt handling capacity",
    lastEdited: "",
    createdAt: "2025-04-23T22:47:33.891Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "40",
    modelWeight: "12",
    parentSectionId: "m9uiwqnoqm5e473zf",
    parentTemplateId: "MORTGAGE_RISK_ASSESSMENT",
    parentRuleId: "DEBT_HANDLING_CAPACITY",
    properties: [
      { name: "<=10", id: "DEBT_HANDLING_CAPACITY_10", score: 20 },
      { name: ">10 and <=20", id: "DEBT_HANDLING_CAPACITY_20", score: 40 },
      { name: ">20 and <=30", id: "DEBT_HANDLING_CAPACITY_30", score: 60 },
      { name: ">30 and <=40", id: "DEBT_HANDLING_CAPACITY_40", score: 80 },
      { name: ">40", id: "DEBT_HANDLING_CAPACITY_40", score: 100 },
    ],
  },
  m9uusebbqob7pzl8mui: {
    id: "m9uusebbqob7pzl8mui",
    name: "Age",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.815Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "AGE",
    properties: [
      { name: "<=25", id: "AGE_25", score: 20 },
      { name: ">25 and <=35", id: "AGE_25_AND_30", score: 60 },
      { name: ">35 and <=45", id: "AGE_35_AND_40", score: 100 },
      { name: ">45 and <=55", id: "AGE_45_AND_55", score: 80 },
      { name: ">55 and <=60", id: "AGE_45_AND_55", score: 60 },
      { name: ">60", id: "AGE_45_AND_55", score: 40 },
    ],
  },
  m9uusebb6nf8ei8pnou: {
    id: "m9uusebb6nf8ei8pnou",
    name: "Education level",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.815Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EDUCATION_LEVEL",
    properties: [
      {
        name: "Graduates & Professional Qualification (MBBS, LLB/Attorney at Law, BSc Eng, ACA, CFA etc.)",
        id: "NO_EDUCATION",
        score: 100,
      },
      {
        name: "Vocational Training / Diploma Holders",
        id: "PRIMARY_EDUCATION",
        score: 80,
      },
      { name: "Advanced Level", id: "SECONDARY_EDUCATION", score: 60 },
      { name: "Up to Ordinary Level", id: "HIGHER_EDUCATION", score: 40 },
      {
        name: "Postgraduate education",
        id: "POSTGRADUATE_EDUCATION",
        score: 100,
      },
    ],
  },
  m9uusebcvcnu764jvkh: {
    id: "m9uusebcvcnu764jvkh",
    name: "Residence type",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.816Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "RESIDENCE_TYPE",
    properties: [
      { name: "Own (Not Mortgaged)", id: "OWN", score: 100 },
      { name: "Own (Mortgaged)", id: "RENT", score: 80 },
      { name: "Parents / Spouse's House", id: "FAMILY", score: 60 },
      { name: "Leased/ Rented", id: "OTHER", score: 40 },
    ],
  },
  m9uusebc3ofowxjf2qw: {
    id: "m9uusebc3ofowxjf2qw",
    name: "Employment status",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.816Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EMPLOYMENT_STATUS",
    properties: [
      { name: "Employed", id: "EMPLOYED", score: 100 },
      { name: "Self Employed", id: "SELF_EMPLOYED", score: 80 },
      { name: "Unemployed", id: "UNEMPLOYED", score: 60 },
      { name: "Retired", id: "RETIRED", score: 40 },
      { name: "Student", id: "STUDENT", score: 20 },
    ],
  },
  m9uusebdvt65d21zf88: {
    id: "m9uusebdvt65d21zf88",
    name: "No of experience in employment",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.817Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "20",
    modelWeight: "7",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EXPERIENCE",
    properties: [
      { name: "<=1", id: "EXPERIENCE_1", score: 20 },
      { name: ">1 and <=3", id: "EXPERIENCE_3", score: 40 },
      { name: ">3 and <=5", id: "EXPERIENCE_5", score: 60 },
      { name: ">5 and <=10", id: "EXPERIENCE_10", score: 80 },
      { name: ">10", id: "EXPERIENCE_10", score: 100 },
    ],
  },
  m9uusebdak9s3veyfj9: {
    id: "m9uusebdak9s3veyfj9",
    name: "Employment Type",
    lastEdited: "",
    createdAt: "2025-04-24T04:19:09.817Z",
    createdBy: "system",
    lastEditedBy: "",
    sectionWeight: "15",
    modelWeight: "5",
    parentSectionId: "m9uup4kpmcslt41tlj",
    parentTemplateId: "RETAIL_SCORE_CARD",
    parentRuleId: "EMPLOYMENT_TYPE",
    properties: [
      {
        name: "Employees of Government and Statutory Bodies",
        id: "PERMANENT",
        score: 100,
      },
      {
        name: "Employees of Private Sector / Professionals with Fixed Income",
        id: "CONTRACT",
        score: 80,
      },
      {
        name: "Professionals with Non-Fixed Income",
        id: "TEMPORARY",
        score: 60,
      },
      { name: "Self-Employed / Own Business", id: "INTERNSHIP", score: 40 },
    ],
  },
};
