#============================
# Stage 1: Build environment
# ============================

FROM node:23.11.0-alpine3.21 AS build


WORKDIR /app

# Install dependencies
COPY package.json ./

RUN npm ci

# Install pnpm globally
RUN npm install -g pnpm@latest-10

# Copy source files
COPY . .

# Build TypeScript project (assumes tsconfig.json is configured)
RUN pnpm run build

# =============================
# Stage 2: Production environment
# =============================

FROM nginx:stable-alpine

# Copy built files from the previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom Nginx config if you have one
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]